In [1]:
import tensorflow as tf

In [2]:
graph1 = tf.Graph()

In [3]:
with graph1.as_default():
    a = tf.constant([2],name = 'constant_a')
    b = tf.constant([3],name = 'constant_b')

In [4]:
a

<tf.Tensor 'constant_a:0' shape=(1,) dtype=int32>

In [5]:
session = tf.Session(graph = graph1)
result = session.run(a)
print(result)
session.close()

[2]


In [6]:
session = tf.Session(graph = graph1)
result = session.run(b)
print(result)
session.close()

[3]


In [7]:
session = tf.Session(graph= graph1)
result = session.run((a,b))
print(result)
session.close()

(array([2], dtype=int32), array([3], dtype=int32))


In [8]:
with graph1.as_default():
    c = tf.add(a,b)
session = tf.Session(graph = graph1)
result = session.run(c)
print(result)
session.close()    

[5]


In [9]:
#without closing the session each time manually
with graph1.as_default():
    c = tf.add(a,b)

with tf.Session(graph = graph1) as session:
    
    result = session.run(c)
    print(c)

Tensor("Add_1:0", shape=(1,), dtype=int32)


In [25]:
graph2 = tf.Graph()
with graph2.as_default():
    Scaler = tf.constant([2])
    Vector = tf.constant([1,2,3])
    Matrix = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
    Tensor = tf.constant( [ [[1,2,3],[2,3,4],[3,4,5]] , [[4,5,6],[5,6,7],[6,7,8]] , [[7,8,9],[8,9,10],[9,10,11]] ] )
with tf.Session(graph= graph2) as session:
    result = session.run(Scaler)
    print("Scalar (1 entry):\n %s \n" % result)
    result = session.run(Vector)
    print("Vector (1 entry):\n %s \n" % result)
    result = session.run(Matrix)
    print("Matrix (1 entry):\n %s \n" % result)
    result = session.run(Tensor)
    print ("Tensor (3x3x3 entries) :\n %s \n" % result)

Scalar (1 entry):
 [2] 

Vector (1 entry):
 [1 2 3] 

Matrix (1 entry):
 [[1 2 3]
 [2 3 4]
 [3 4 5]] 

Tensor (3x3x3 entries) :
 [[[ 1  2  3]
  [ 2  3  4]
  [ 3  4  5]]

 [[ 4  5  6]
  [ 5  6  7]
  [ 6  7  8]]

 [[ 7  8  9]
  [ 8  9 10]
  [ 9 10 11]]] 



In [35]:
graph3 = tf.Graph()
with graph3.as_default():
    Matrix_one  = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
    Matrix_two  = tf.constant([[4,5,6],[5,6,7],[6,7,8]])
    add_operation = tf.add(Matrix_one, Matrix_two)
    mul_operation = Matrix_one * Matrix_two
    sub_operation = tf.subtract(Matrix_one, Matrix_two)
    
with tf.Session(graph = graph3) as session:
    result = session.run(mul_operation)
    print(result)
    

[[ 4 10 18]
 [10 18 28]
 [18 28 40]]
